#
# BASE CONFIGURATION
#

# `base_url` should only be changed if your site isn't hosted at the root of a domain.
# `domain` is used to generate absolute URLs. (required to generate a valid feed)
#
#   Example:
#       http://my-site.com/
#           base_url: /
#           domain: my-site.com
#       http://my-site.com/my-blog/
#           base_url: /my-blog/
#           domain: my-site.com
base_url: /
domain: the.emptybox.dk


#
# METADATA
#

# Used in header meta tags and the site feed. (required to generate a valid feed)
author: 
  name: Christian Place
  link: http://christianplace.dk
# A description of your site to be used in header meta tags.
description:
# Used in the site feed.
email:
# Your site's subtitle.
subtitle: Notes and thoughts put in a box
# Your site's title. (required to generate a valid feed)
title: The Empty Box


#
# THIRD PARTY SETTINGS
#

# If you'd like to enable Google Analytics for your site, set this to your tracking code.
analytics:


